import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { JwtContextProvider } from "@/store/jwtContext";
import { LecturerContextProvider } from "@/store/lecturerContext";
import { ErrorContextProvider } from "@/store/globalErrorContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Attendnow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ErrorContextProvider>
          <JwtContextProvider>
            <LecturerContextProvider>
              <div
                className="w-full h-[30px] absolute top-0 right-0"
                style={{ WebkitAppRegion: "drag" }}
              ></div>
              {children}
            </LecturerContextProvider>
          </JwtContextProvider>
        </ErrorContextProvider>
      </body>
    </html>
  );
}
